name: reactor-crw

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: go test -v ./... --tags unit

    - name: Build
      env:
        CGO_ENABLED: 0
        BINARY_NAME: reactor-crw
      run: go build -o "$BINARY_NAME-$RUNNER_OS" cmd/main.go
